### ISSUE TITLE
error: 'IsingV1Puzzle' is not a member of 'puzzler'

### ISSUE THREAD

**Issue by vincentooi88** [HPCE/hpce-2018-cw5#10]
We've created a copy of one of the puzzle hpp files and change the code to the following:
```
class IsingProvider
  : public puzzler::IsingV1Puzzle
```

However we get this error:
 error: 'IsingV1Puzzle' is not a member of 'puzzler'
   Register("isingv1.ref", std::make_shared<puzzler::IsingV1Puzzle>());

Is there something else we should be adding/changing?

**Comment by tnugent97** [comment]
If you have copied one of the files in the provider folder, then these are not in the `puzzler` namespace. See #11 for more explanation on which files you should be editing.

**Comment by jjd06** [comment]
... and #2 for more namespace-related fun.
