### ISSUE TITLE
Are we allowed to parallelize functions other than ReferenceExecute

### ISSUE THREAD

**Issue by Shuruili** [HPCE/hpce-2018-cw5#12]
For example rank.hpp do we allowed to parallelize the iteration function which is called inside the ReferenceExecute function?

**Comment by jjd06** [comment]
Absolutely -- you'd have a hard time getting speedups if you didn't! However you should create your own versions of these methods in the `provider` directory (or implement them inside your `Execute` methods); the `ReferenceExecute` methods, along with everything else inside `include`, should be left as-is.
