### ISSUE TITLE
First Test Round

### ISSUE THREAD

**Issue by swarth100** [HPCE/hpce-2018-cw5#13]
I might mave missed it, should this information have already been communicated, but when should we expect the first test run to occur?

**Comment by tnugent97** [comment]
Im pretty sure there are no test runs for cw5 and cw6

**Comment by swarth100** [comment]
I'm just asking because we seem to experience severely unreliable performance on AWS instances with GPU (p3 and g3).

To the point that what is severly faster with opencl running on a GTX 1080 or 970, is several times slower on AWS GPU (i.e. just querying the GPU seems to take a long time, `nvidia-smi` takes up to 5 seconds to return a result).

Additionally we cannot seem to replicate the performance of `rank` and `integral` for the reference puzzle. On the machines/instances we test on, `decompose` and `ising` references get very similar results to what is reported (with the given sequence generation), the other two no.

Has anyone been experiencing similar issues?
1) AWS GPUs being much slower to query than normal GPUs
2) Achieving the correct scores for the reference `rank` and `integral` puzzles

I just think a single test run can give us an idea of how good or bad our implementations _actually_ are. We have seen in the past that occasionally the testing environment wasn't exactly behaving as we had expected (with much shorter tests or tests run in parallel), so the testing system which we might be using to optimise our code might be flawed and give completely different results to what will be actually used for grading.

**Comment by AlexMontgomerie** [comment]
yeah we're getting the same issue. The reference execution for integral scores the same for what there is for rank, and vice versa. Maybe the names in the tables are swapped around? Otherwise, the reference score for decompose and ising seem fairly accurate when run on the AWS instance.

**Comment by jjd06** [comment]
I'm not doing performance test runs for CW5 or CW6. I'm intending to do some very basic sanity checking (probably just to ensure that your code builds and runs successfully), but I haven't scripted this up yet.

There is a small typo in the table (in the sequence for `rank`), which I will fix, but I've just rerun the reference implementations on a g3.4xlarge instance and the performance numbers are (with a bit of noise) correct. Are you sure that you're timing the right thing (just `puzzle->Execute`) with scales generated according to the given sequences?
