### ISSUE TITLE
Timing of CreateInput

### ISSUE THREAD

**Issue by rmurai0610** [HPCE/hpce-2018-cw5#14]
When measuring the performance metric, should execution time of CreateInput() be considered?
If so, are we allowed to override the function to get some speedup?

**Comment by jjd06** [comment]
No, it shouldn't. Only the timing of `puzzle->Execute` calls matters.

**Comment by rmurai0610** [comment]
Thank you for the reply. 
In this case, are we stilled allowed to make modifications to CreateInput() and would this changes be reflected in the testing?

**Comment by jjd06** [comment]
You could but, even if they were executed (which they wouldn't be), such changes wouldn't make a difference to your performance, so I'd suggest that such things aren't a good use of your time.

**Comment by rmurai0610** [comment]
I have noticed that changing the input would allow some of the puzzle to be solved more easily. 
However, if it is the case that our CreateInput is not called, I guess there is no point making these modification.
