### ISSUE TITLE
nvidia-persistenced

### ISSUE THREAD

**Issue by swarth100** [HPCE/hpce-2018-cw5#19]
We see a massive performance difference for Opencl code if the following commands are run to configure the GPU on the AWS `g3.4xlarge` instance:
```
[ec2-user ~]$ sudo nvidia-persistenced
[ec2-user ~]$ sudo nvidia-smi --auto-boost-default=0
[ec2-user ~]$ sudo nvidia-smi -ac 2505,1177
```

They are mentioned within this link:
https://docs.aws.amazon.com/en_us/AWSEC2/latest/UserGuide/optimize_gpu.html

As can be read within the `nvidia-persistenced` utility:

> A Linux daemon utility, nvidia-persistenced, addresses an undesirable side effect of the NVIDIA kernel driver behavior in certain computing environments. Whenever the NVIDIA device resources are no longer in use, the NVIDIA kernel driver will tear down the device state. Normally, this is the intended behavior of the device driver, but for some applications, the latencies incurred by repetitive device initialization can significantly impact performance.

A very simple example of the benefits it gives is that if we query the GPU normally (without these configurations), `nvidia-smi` takes 3-5 seconds to give us a result (having to boot up the GPU drivers). Once we run this command it returns instantaneously.
The same applies to every time we query the drivers for the first time from opencl (i.e. for every new sequence number).

Can we assume the testing/grading AWS GPU to have been configured this way?

**Comment by jjd06** [comment]
This shouldn't be an issue during testing because your puzzle objects won't be destroyed between calls to `Execute`. This assumes that you're not doing things like creating contexts inside `Execute`, of course.

**Comment by swarth100** [comment]
Hello,

A quick update:
We have ported all of our opencl initialisation code to the constructor and we only time the execution of the Execute method.

Still, when we run with the `nvidia` optimisations outlined above we get a 5-10% performance increase (on problems such as `ising` and `integral`).

Could these optimisations be run on the server running the tests?
They are suggested by AWS themselves and in our case it does end up yielding higher performance.

Anyone having the same issue?

**Comment by jjd06** [comment]
I did try a few performance tests with/without these, and didn't see any noticeable difference. I don't see any reason not to use them, though, so will add them to my AWS setup script. Note that I would've had to recalibrate the performance figures for assessment anyway (due to software updates, etc.), so this just gives me another reason to do that.

**Comment by swarth100** [comment]
Thank you so much for this!
