### ISSUE TITLE
reference rank implementation sometimes won't converge

### ISSUE THREAD

**Issue by sprack2020** [HPCE/hpce-2018-cw5#24]
The reference rank implementation is bugged for small values.
The thing segfaults when n=0
for n~2-10 some inputs will not converge such that tol > dist
![image](https://user-images.githubusercontent.com/15960779/53595907-6c52a700-3b96-11e9-99ac-c0efe262c343.png)
(^^ running n=2 with rank.ref for about 20 seconds ^^)
Also comparing the output of different implementations will sometimes fail for n<50 due to floating point arithmetic.
Does this mean we can assume the random inputs will have n > 50?

**Comment by tnugent97** [comment]
I'm not sure I can reproduce your results. Is this with the reference implementation or one of your engines?
Also what do you mean by n? If you mean the equation in the readme (`50+(i*30+U*20)^2`), then this will only be 950 at it's smallest (i >= 1).
I have experienced the floating point issues for small input, particularly when using the GPU, but not really sure what to do about it :(

**Comment by sprack2020** [comment]
I can't read. Thank you.
