### ISSUE TITLE
Ptx Error?

### ISSUE THREAD

**Issue by jaki95** [HPCE/hpce-2018-cw5#25]
Getting the following error trying to compile the code with OpenCL

``
ptxas application ptx input, line 237; error   : Call has wrong number of parameters
ptxas application ptx input, line 237; error   : Type of argument does not match formal parameter '%VAParam'
ptxas fatal   : Ptx assembly aborted due to errors
``

Any ideas what this might be given by?

**Comment by DiederikVink** [comment]
Have a look at this issue from 2 years ago: https://github.com/HPCE/hpce-2016-cw6/issues/32
Looks like its the same/similar issue
