### ISSUE TITLE
Clarification on Performance Metric

### ISSUE THREAD

**Issue by tnugent97** [HPCE/hpce-2018-cw5#6]
In the lectures it sounded as if each puzzle gets 60 seconds to execute as many executions as possible (with increasing problem size). 
The Performance Metric section of the readme suggests that actually each puzzle execution (for a given problem size) is capped at 60 seconds, so the 60 second timer is reset for each execution of the puzzle, and this finishes when a problem size is reached that causes the execution to go over 60 seconds.
I hope I explained that ok.
I assume we should go by the explanation in the README rather than my weird interpretation from the lectures?
Thanks!

Edit: Actually just read through it again and the interpretation from the lectures seems right. t_j is actually the sum of all previous time steps, so when this exceeds 60 seconds, we finish

**Comment by jjd06** [comment]
My explanation was slightly simplified (I didn't mention the fractional complication), but I think it was largely correct. As you've said,

`t_j = f(1) + f(2) + ... + f(j)`,

so the sequence

`t_1, t_2, ... , t_j`

is actually a set of timestamps starting from 0 (i.e. cumulative), not the individual run times. That would be

`f(1), f(2), ... , f(j)`

instead.
