### ISSUE TITLE
How accuracte does it need to be?

### ISSUE THREAD

**Issue by AlexMontgomerie** [HPCE/hpce-2018-cw5#7]
Are we allowed to change data types? or does it have to be as is described in the reference? For instance, can fixed-point be used instead of floating point to get around issues with atomic float operations?

Thanks,
Alex

**Comment by jjd06** [comment]
Each puzzle's `CompareOutputs` method, as implemented in `include/puzzler/puzzles/<name>.hpp`, has to return `true`. You can certainly explore replacing the floats: the puzzles that use them have (well defined) output tolerances. They may not be particularly loose, however....

**Comment by AlexMontgomerie** [comment]
Ok, cheers
